###
GET http://localhost:8080/videos?api_key=32466d85-c74a-4004-8864-0d31ddf91185 HTTP/1.1
###
POST http://localhost:8080/videos?api_key=32466d85-c74a-4004-8864-0d31ddf91185 HTTP/1.1
Content-Type: application/json

{
    "title":"Industry-Leading Tech & Coding Bootcamps",
    "description":"BrainStation coding bootcamps are 400-hour, project-based programs that have helped thousands of bootcamp students launch new careers in the tech industry. Gain in-demand technical skills with full-time or part-time bootcamps",
    "channel": "BrainStation",
    "image": "http://localhost:8080/images/image9.jpg",
    "views": "106,000",
    "likes": "8,080",
    "duration": "0:20",
    "video": "http://localhost:8080/BrainStation Sample Video.mp4",
    "comments": []
}

###
GET http://localhost:8080/videos/84e96018-4022-434e-80bf-000ce4cd12b8?api_key=32466d85-c74a-4004-8864-0d31ddf91185 HTTP/1.1
###
GET http://localhost:8080/videos/000ce4cd12b8?api_key=32466d85-c74a-4004-8864-0d31ddf91185 HTTP/1.1

###
POST http://localhost:8080/videos/84e96018-4022-434e-80bf-000ce4cd12b8/comments?api_key=32466d85-c74a-4004-8864-0d31ddf91185 HTTP/1.1
Content-Type: application/json

{
    "name": "Trudy Jankowski",
    "comment": "I really enjoyed this video! Thanks for posting"
}

###
DELETE http://localhost:8080/videos/84e96018-4022-434e-80bf-000ce4cd12b8/comments/0184de5d-e8fd-4f16-a8c3-b6a7c87d9abc?api_key=32466d85-c74a-4004-8864-0d31ddf91185 HTTP/1.1

###
PUT http://localhost:8080/videos/84e96018-4022-434e-80bf-000ce4cd12b8/likes?api_key=32466d85-c74a-4004-8864-0d31ddf91185 HTTP/1.1


